CREATE SCHEMA api;
CREATE SCHEMA backend;

DROP TABLE IF EXISTS api.school CASCADE;
CREATE TABLE api.school (
	id SERIAL PRIMARY KEY,
	school_name varchar NOT NULL,
	contact_person varchar,
	address varchar,
	phone bigint,
	email varchar,
	date_of_initial_contact timestamp,
	date_modified timestamp
);


DROP TABLE IF EXISTS api.users CASCADE;
CREATE TABLE api.users (
	id SERIAL PRIMARY KEY,
	school_id int REFERENCES api.school, -- Null for Super admin
	firstname varchar,
  lastname varchar,
	phone bigint,
  picture_link text
);

DROP TABLE IF EXISTS backend.user_roles CASCADE;
CREATE TABLE backend.user_roles (
	id int PRIMARY KEY,
	role_name varchar
);

INSERT INTO backend.user_roles (id, role_name) VALUES (1, 'super_admin');
INSERT INTO backend.user_roles (id, role_name) VALUES (2, 'school_admin');
INSERT INTO backend.user_roles (id, role_name) VALUES (3, 'instructor');
INSERT INTO backend.user_roles (id, role_name) VALUES (4, 'student');

DROP TABLE IF EXISTS backend.user_account CASCADE;
CREATE TABLE backend.user_account (
	id int REFERENCES api.users,
	password text NOT NULL,
	role_id int REFERENCES backend.user_roles NOT NULL
);


-- TABLE IS TO STORE BACKEND INFO
CREATE TABLE IF NOT EXISTS api.track_path (
	id uuid,
	data jsonb,
	insert_date timestamp default current_timestamp
);



DROP TABLE IF EXISTS api.driver_score CASCADE;
CREATE TABLE api.driver_score(
  id SERIAL PRIMARY KEY,
  driver_id int REFERENCES api.users,
  total_score float,
  progression float,
  driving_time float,
  d1_focus float,
  f2_efficiency float,
  d3_anticipation float,
  d4_legality float,
  d5_progression float,
  r_turn_score float,
  r_turn_speed float,
  r_turn_acc float,
  l_turn_speed float,
  l_turn_acc float,
  l_turn_score float,
  u_turn_speed float,
  u_turn_acc float,
  u_turn_score float,
  r_lc_speed float,
  r_lc_acc float,
  r_lc_score float,
  l_lc_speed float,
  l_lc_acc float,
  l_lc_score float,
  creation_date timestamp,
  date_modified timestamp
);

CREATE VIEW api.drivers_v AS (
  SELECT u.*
  FROM api.USERS as u
  JOIN backend.user_account as a on a.id=u.id
  WHERE a.role_id = 4
  AND u.school_id = current_setting('jwt.claims.school_id')::integer
);

DROP TABLE IF EXISTS api.route CASCADE;
CREATE TABLE api.route (
  id SERIAL PRIMARY KEY,
  school_id int REFERENCES api.school,
  route_name varchar,
  creation_date timestamp
);

DROP TABLE IF EXISTS api.waypoint_subjects CASCADE;
CREATE TABLE api.waypoint_subjects(
  id SERIAL PRIMARY KEY,
  subject_name VARCHAR
);

DROP TABLE IF EXISTS api.waypoints CASCADE;
CREATE TABLE api.waypoints (
  id SERIAL PRIMARY KEY,
  route_id int REFERENCES api.route,
  wp_lat float,
  wp_long float,
  sequence int, -- waypoints order sequence
  waypoint_subject_id int REFERENCES api.waypoint_subjects,
  is_last bool
);



CREATE TABLE backend.track (
  id uuid PRIMARY KEY,
  driver_id int NOT NULL REFERENCES api.users,
  device_id int NOT NULL REFERENCES api.device
  DROP TABLE IF EXISTS backend.track CASCADE;
);


DROP TABLE IF EXISTS backend.processed_results CASCADE;
CREATE TABLE backend.processed_results (
id uuid PRIMARY KEY REFERENCES backend.track,
type varchar,
prob float,
score	float,
d float,
s_utc	float,
e_utc	float,
event_acc	float,
s_spd	float,
e_spd float,
s_crs float,
e_crs float,
s_lat float,
e_lat float,
s_long float,
e_long float,
s_alt float,
e_alt float,
sec1_s_spd float,
sec1_e_spd float,
sec1_spd_bin float,
sec1_acc_z float,
sec1_dec_z float,
sec1_lat_lt_z	float,
sec1_lat_rt_z	float,
sec2_s_spd float,
sec2_e_spd float,
sec2_spd_bin float,
sec2_acc_z float,
sec2_dec_z float,
sec2_lat_lt_z	float,
sec2_lat_rt_z	float,
sec3_s_spd float,
sec3_e_spd float,
sec3_spd_bin float,
sec3_acc_z float,
sec3_dec_z float,
sec3_lat_lt_z	float,
sec3_lat_rt_z	float,
acc_1	float,
acc_2	float,
acc_3	float,
acc_4	float,
acc_5	float,
acc_6	float,
acc_7	float,
acc_8	float,
acc_9 float,
acc_10 float,
acc_11 float,
acc_12 float,
acc_13 float,
acc_14 float,
acc_15 float,
acc_16 float,
acc_17 float,
acc_18 float,
acc_19 float,
acc_20 float,
lfc_1	float,
lfc_2	float,
lfc_3	float,
lfc_4	float,
lfc_5	float,
lfc_6	float,
lfc_7	float,
lfc_8	float,
lfc_9 float,
lfc_10 float,
lfc_11 float,
lfc_12 float,
lfc_13 float,
lfc_14 float,
lfc_15 float,
lfc_16 float,
lfc_17 float,
lfc_18 float,
lfc_19 float,
lfc_20 float,
spd_1	float,
spd_2	float,
spd_3	float,
spd_4	float,
spd_5	float,
spd_6	float,
spd_7	float,
spd_8	float,
spd_9 float,
spd_10 float,
spd_11 float,
spd_12 float,
spd_13 float,
spd_14 float,
spd_15 float,
spd_16 float,
spd_17 float,
spd_18 float,
spd_19 float,
spd_20 float,
crs_1	float,
crs_2	float,
crs_3	float,
crs_4	float,
crs_5	float,
crs_6	float,
crs_7	float,
crs_8	float,
crs_9 float,
crs_10 float,
crs_11 float,
crs_12 float,
crs_13 float,
crs_14 float,
crs_15 float,
crs_16 float,
crs_17 float,
crs_18 float,
crs_19 float,
crs_20 float,
rot_1	float,
rot_2	float,
rot_3	float,
rot_4	float,
rot_5	float,
rot_6	float,
rot_7	float,
rot_8	float,
rot_9	float,
rot_10 float,
rot_11 float,
rot_12 float,
rot_13 float,
rot_14 float,
rot_15 float,
rot_16 float,
rot_17 float,
rot_18 float,
rot_19 float,
rot_20 float
);

DROP TABLE IF EXISTS backend.cleaned_results CASCADE;
CREATE TABLE backend.cleaned_results (
id uuid PRIMARY KEY REFERENCES backend.track,
type varchar,
score	float,
prob float,
d float,
s_utc	float,
e_utc	float,
event_acc	float,
s_spd	float,
e_spd float,
s_crs float,
e_crs float,
s_lat float,
e_lat float,
s_long float,
e_long float,
s_alt float,
e_alt float,
sec1_s_spd float,
sec1_e_spd float,
sec1_spd_bin float,
sec1_acc_z float,
sec1_dec_z float,
sec1_lat_lt_z	float,
sec1_lat_rt_z	float,
sec2_s_spd float,
sec2_e_spd float,
sec2_spd_bin float,
sec2_acc_z float,
sec2_dec_z float,
sec2_lat_lt_z	float,
sec2_lat_rt_z	float,
sec3_s_spd float,
sec3_e_spd float,
sec3_spd_bin float,
sec3_acc_z float,
sec3_dec_z float,
sec3_lat_lt_z	float,
sec3_lat_rt_z	float,
acc_1	float,
acc_2	float,
acc_3	float,
acc_4	float,
acc_5	float,
acc_6	float,
acc_7	float,
acc_8	float,
acc_9 float,
acc_10 float,
acc_11 float,
acc_12 float,
acc_13 float,
acc_14 float,
acc_15 float,
acc_16 float,
acc_17 float,
acc_18 float,
acc_19 float,
acc_20 float,
lfc_1	float,
lfc_2	float,
lfc_3	float,
lfc_4	float,
lfc_5	float,
lfc_6	float,
lfc_7	float,
lfc_8	float,
lfc_9 float,
lfc_10 float,
lfc_11 float,
lfc_12 float,
lfc_13 float,
lfc_14 float,
lfc_15 float,
lfc_16 float,
lfc_17 float,
lfc_18 float,
lfc_19 float,
lfc_20 float,
spd_1	float,
spd_2	float,
spd_3	float,
spd_4	float,
spd_5	float,
spd_6	float,
spd_7	float,
spd_8	float,
spd_9 float,
spd_10 float,
spd_11 float,
spd_12 float,
spd_13 float,
spd_14 float,
spd_15 float,
spd_16 float,
spd_17 float,
spd_18 float,
spd_19 float,
spd_20 float,
crs_1	float,
crs_2	float,
crs_3	float,
crs_4	float,
crs_5	float,
crs_6	float,
crs_7	float,
crs_8	float,
crs_10 float,
crs_11 float,
crs_12 float,
crs_9 float,
crs_13 float,
crs_14 float,
crs_15 float,
crs_16 float,
crs_17 float,
crs_18 float,
crs_19 float,
crs_20 float,
rot_1	float,
rot_2	float,
rot_3	float,
rot_4	float,
rot_5	float,
rot_6	float,
rot_7	float,
rot_8	float,
rot_9	float,
rot_10 float,
rot_11 float,
rot_12 float,
rot_13 float,
rot_14 float,
rot_15 float,
rot_16 float,
rot_17 float,
rot_18 float,
rot_19 float,
rot_20 float
);

DROP TABLE IF EXISTS api.display_results CASCADE;
CREATE TABLE api.display_results (
id uuid PRIMARY KEY REFERENCES backend.track,
s_crs float,
e_crs float,
s_lat float,
e_lat float,
s_long float,
e_long float,
s_alt float,
e_alt float,
sec1_s_spd float,
sec1_e_spd float,
sec1_spd_bin float,
sec1_acc_z float,
sec1_dec_z float,
sec1_lat_lt_z	float,
sec1_lat_rt_z	float,
sec2_s_spd float,
sec2_e_spd float,
sec2_spd_bin float,
sec2_acc_z float,
sec2_dec_z float,
sec2_lat_lt_z	float,
sec2_lat_rt_z	float,
sec3_s_spd float,
sec3_e_spd float,
sec3_spd_bin float,
sec3_acc_z float,
sec3_dec_z float,
sec3_lat_lt_z	float,
sec3_lat_rt_z	float,
acc_1	float,
acc_2	float,
acc_3	float,
acc_4	float,
acc_5	float,
acc_6	float,
acc_7	float,
acc_8	float,
acc_9 float,
acc_10 float,
acc_11 float,
acc_12 float,
acc_13 float,
acc_14 float,
acc_15 float,
acc_16 float,
acc_17 float,
acc_18 float,
acc_19 float,
acc_20 float,
lfc_1	float,
lfc_2	float,
lfc_3	float,
lfc_4	float,
lfc_5	float,
lfc_6	float,
lfc_7	float,
lfc_8	float,
lfc_9 float,
lfc_10 float,
lfc_11 float,
lfc_12 float,
lfc_13 float,
lfc_14 float,
lfc_15 float,
lfc_16 float,
lfc_17 float,
lfc_18 float,
lfc_19 float,
lfc_20 float,
spd_1	float,
spd_2	float,
spd_3	float,
spd_4	float,
spd_5	float,
spd_6	float,
spd_7	float,
spd_8	float,
spd_9 float,
spd_10 float,
spd_11 float,
spd_12 float,
spd_13 float,
spd_14 float,
spd_15 float,
spd_16 float,
spd_17 float,
spd_18 float,
spd_19 float,
spd_20 float,
crs_1	float,
crs_2	float,
crs_3	float,
crs_4	float,
crs_5	float,
crs_6	float,
crs_7	float,
crs_8	float,
crs_9 float,
crs_10 float,
crs_11 float,
crs_12 float,
crs_13 float,
crs_14 float,
crs_15 float,
crs_16 float,
crs_17 float,
crs_18 float,
crs_19 float,
crs_20 float,
rot_1	float,
rot_2	float,
rot_3	float,
rot_4	float,
rot_5	float,
rot_6	float,
rot_7	float,
rot_8	float,
rot_9	float,
rot_10 float,
rot_11 float,
rot_12 float,
rot_13 float,
rot_14 float,
rot_15 float,
rot_16 float,
rot_17 float,
rot_18 float,
rot_19 float,
rot_20 float
);
